devtools::use_testthat()
devtools::use_data()
# devtools::use_github()
devtools::use_build_ignore()
devtools::use_code_of_conduct()
devtools::use_travis()
devtools::use_coverage()
devtools::use_revdep()
devtools::use_package_doc()
devtools::use_vignette()
devtools::use_cran_badge()
